server:
 port: 8091

spring:
 application:
  name: cursos
 banner:
  location: classpath:banner/banner.txt

# Config Server
 config:
  import: "configserver:"
  cloud:
  cloud.config.uri: http://localhost:8888